# spring.application.name=api-mascotas-prod


# spring.datasource.url=jdbc:mysql://localhost:3306/mascotas
# spring.datasource.username=root
# spring.datasource.password=014V

# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=true

# server.port=8089

#poner la que cree Polirritmico de docker 
