# Documentation Metadata
springdoc.openapi.info.title=Pets Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description=Microservicio de gestión de mascotas. \
                                   Expone operaciones CRUD de mascotas, razas y especies.
springdoc.openapi.info.contact.name=DuocUC FullStack 1
springdoc.openapi.info.contact.email=soporte@duoc.cl
springdoc.openapi.info.license.name=MIT
springdoc.openapi.info.license.url=https://opensource.org/licenses/MIT

# Actuator
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=${springdoc.openapi.info.title}
info.app.environment=${spring.profiles.active}
